-- Create the logs table
CREATE TABLE logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  message TEXT,
  error JSONB
);

-- Enable Row Level Security
ALTER TABLE logs ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow authenticated users to insert logs
CREATE POLICY "Allow authenticated users to insert logs"
ON logs
FOR INSERT
TO authenticated
WITH CHECK (true);
