BEGIN;

-- ============================================================================
-- DISPLAY V3 RUNTIME (CHAMADAS COM GARANTIA FIFO + ACK POR TELA)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.display_call_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sequence bigint GENERATED BY DEFAULT AS IDENTITY,
  patient_id uuid NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  destination text NOT NULL,
  called_by uuid NOT NULL REFERENCES auth.users(id),
  call_count integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT display_call_events_sequence_key UNIQUE (sequence)
);

CREATE TABLE IF NOT EXISTS public.display_sessions (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  device_name text NOT NULL DEFAULT 'display',
  heartbeat_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.display_call_acks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES public.display_call_events(id) ON DELETE CASCADE,
  session_id uuid NOT NULL REFERENCES public.display_sessions(id) ON DELETE CASCADE,
  status text NOT NULL CHECK (status IN ('playing', 'played', 'failed')),
  error_message text,
  acknowledged_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT display_call_acks_unique_status UNIQUE (event_id, session_id, status)
);

CREATE INDEX IF NOT EXISTS idx_display_call_events_sequence ON public.display_call_events(sequence);
CREATE INDEX IF NOT EXISTS idx_display_call_events_created_at ON public.display_call_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_display_sessions_heartbeat ON public.display_sessions(heartbeat_at DESC);
CREATE INDEX IF NOT EXISTS idx_display_call_acks_session_event ON public.display_call_acks(session_id, event_id);
CREATE INDEX IF NOT EXISTS idx_display_call_acks_status ON public.display_call_acks(status, acknowledged_at DESC);

ALTER TABLE public.display_call_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.display_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.display_call_acks ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'display_call_events'
      AND policyname = 'Display call events are readable by authenticated users'
  ) THEN
    CREATE POLICY "Display call events are readable by authenticated users"
      ON public.display_call_events
      FOR SELECT
      TO authenticated
      USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'display_sessions'
      AND policyname = 'Display sessions are accessible by owner'
  ) THEN
    CREATE POLICY "Display sessions are accessible by owner"
      ON public.display_sessions
      FOR ALL
      TO authenticated
      USING (user_id = auth.uid())
      WITH CHECK (user_id = auth.uid());
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'display_call_acks'
      AND policyname = 'Display call acks are readable by authenticated users'
  ) THEN
    CREATE POLICY "Display call acks are readable by authenticated users"
      ON public.display_call_acks
      FOR SELECT
      TO authenticated
      USING (true);
  END IF;
END
$$;

-- ============================================================================
-- RPCs V3
-- ============================================================================

CREATE OR REPLACE FUNCTION public.display_enqueue_call(
  p_patient_id uuid,
  p_destination text,
  p_called_by uuid DEFAULT NULL
)
RETURNS TABLE (
  event_id uuid,
  sequence bigint,
  patient_id uuid,
  patient_name text,
  destination text,
  call_count integer,
  created_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_patient public.patients;
  v_event public.display_call_events;
  v_called_by uuid;
BEGIN
  IF p_patient_id IS NULL THEN
    RAISE EXCEPTION 'patient_id é obrigatório' USING ERRCODE = '22023';
  END IF;

  IF COALESCE(trim(p_destination), '') = '' THEN
    RAISE EXCEPTION 'destination é obrigatório' USING ERRCODE = '22023';
  END IF;

  v_called_by := COALESCE(p_called_by, auth.uid());
  IF v_called_by IS NULL THEN
    RAISE EXCEPTION 'called_by é obrigatório' USING ERRCODE = '22023';
  END IF;

  SELECT *
  INTO v_patient
  FROM public.patients
  WHERE id = p_patient_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Paciente não encontrado' USING ERRCODE = 'P0002';
  END IF;

  UPDATE public.patients
  SET status = 'Chamado',
      destination = p_destination,
      "callCount" = COALESCE(v_patient."callCount", 0) + 1
  WHERE id = p_patient_id
  RETURNING * INTO v_patient;

  INSERT INTO public.calls(patient_id, location)
  VALUES (p_patient_id, p_destination);

  INSERT INTO public.display_call_events(patient_id, destination, called_by, call_count)
  VALUES (p_patient_id, p_destination, v_called_by, v_patient."callCount")
  RETURNING * INTO v_event;

  RETURN QUERY
  SELECT
    v_event.id,
    v_event.sequence,
    v_event.patient_id,
    v_patient.name,
    v_event.destination,
    v_event.call_count,
    v_event.created_at;
END;
$$;

CREATE OR REPLACE FUNCTION public.display_register_session(
  p_session_id uuid,
  p_user_id uuid,
  p_device_name text DEFAULT NULL
)
RETURNS public.display_sessions
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session public.display_sessions;
BEGIN
  IF p_session_id IS NULL THEN
    RAISE EXCEPTION 'session_id é obrigatório' USING ERRCODE = '22023';
  END IF;

  IF p_user_id IS NULL THEN
    RAISE EXCEPTION 'user_id é obrigatório' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.display_sessions AS s (
    id,
    user_id,
    device_name,
    heartbeat_at,
    created_at,
    updated_at
  )
  VALUES (
    p_session_id,
    p_user_id,
    COALESCE(NULLIF(trim(p_device_name), ''), 'display'),
    now(),
    now(),
    now()
  )
  ON CONFLICT (id) DO UPDATE
  SET user_id = EXCLUDED.user_id,
      device_name = EXCLUDED.device_name,
      heartbeat_at = now(),
      updated_at = now()
  RETURNING s.* INTO v_session;

  RETURN v_session;
END;
$$;

CREATE OR REPLACE FUNCTION public.display_heartbeat(
  p_session_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.display_sessions
  SET heartbeat_at = now(),
      updated_at = now()
  WHERE id = p_session_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Sessão de display não encontrada' USING ERRCODE = 'P0002';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.display_get_pending_calls(
  p_session_id uuid,
  p_limit integer DEFAULT 20
)
RETURNS TABLE (
  event_id uuid,
  sequence bigint,
  patient_id uuid,
  patient_name text,
  destination text,
  call_count integer,
  created_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT
    e.id,
    e.sequence,
    e.patient_id,
    p.name,
    e.destination,
    e.call_count,
    e.created_at
  FROM public.display_call_events e
  JOIN public.patients p ON p.id = e.patient_id
  LEFT JOIN public.display_call_acks played
    ON played.event_id = e.id
   AND played.session_id = p_session_id
   AND played.status = 'played'
  WHERE played.id IS NULL
  ORDER BY e.sequence ASC
  LIMIT GREATEST(COALESCE(p_limit, 20), 1);
END;
$$;

CREATE OR REPLACE FUNCTION public.display_ack_call(
  p_session_id uuid,
  p_event_id uuid,
  p_status text,
  p_error_message text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_status NOT IN ('playing', 'played', 'failed') THEN
    RAISE EXCEPTION 'status inválido: %', p_status USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.display_call_acks(
    event_id,
    session_id,
    status,
    error_message,
    acknowledged_at
  )
  VALUES (
    p_event_id,
    p_session_id,
    p_status,
    p_error_message,
    now()
  )
  ON CONFLICT (event_id, session_id, status)
  DO UPDATE
    SET error_message = EXCLUDED.error_message,
        acknowledged_at = EXCLUDED.acknowledged_at;
END;
$$;

CREATE OR REPLACE FUNCTION public.display_cleanup_runtime()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_day_start timestamptz;
BEGIN
  v_day_start := (date_trunc('day', now() AT TIME ZONE 'America/Sao_Paulo') AT TIME ZONE 'America/Sao_Paulo');

  DELETE FROM public.display_call_acks
  WHERE acknowledged_at < v_day_start;

  DELETE FROM public.display_call_events
  WHERE created_at < v_day_start;

  DELETE FROM public.display_sessions
  WHERE heartbeat_at < now() - interval '24 hours';
END;
$$;

CREATE OR REPLACE FUNCTION public.display_cleanup_tts_cache()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_supabase_url text;
  v_service_role_key text;
BEGIN
  SELECT decrypted_secret
  INTO v_supabase_url
  FROM vault.decrypted_secrets
  WHERE name = 'supabase_url'
  LIMIT 1;

  SELECT decrypted_secret
  INTO v_service_role_key
  FROM vault.decrypted_secrets
  WHERE name = 'service_role_key'
  LIMIT 1;

  IF COALESCE(v_supabase_url, '') = '' OR COALESCE(v_service_role_key, '') = '' THEN
    RAISE NOTICE 'display_cleanup_tts_cache ignorado: secrets supabase_url/service_role_key não encontrados no vault.';
    RETURN;
  END IF;

  PERFORM net.http_post(
    url := format('%s/functions/v1/cleanup-tts-bucket', rtrim(v_supabase_url, '/')),
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', format('Bearer %s', v_service_role_key)
    ),
    body := '{}'::jsonb
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.display_enqueue_call(uuid, text, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.display_register_session(uuid, uuid, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.display_heartbeat(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.display_get_pending_calls(uuid, integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.display_ack_call(uuid, uuid, text, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.display_cleanup_runtime() TO service_role;
GRANT EXECUTE ON FUNCTION public.display_cleanup_tts_cache() TO service_role;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'display_call_events'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE ONLY public.display_call_events;
  END IF;
END
$$;

-- ============================================================================
-- AVISOS: REMOÇÃO DEFINITIVA DE YOUTUBE
-- ============================================================================

DELETE FROM public.warnings
WHERE media_type = 'youtube';

ALTER TABLE public.warnings
DROP CONSTRAINT IF EXISTS warnings_media_type_check;

ALTER TABLE public.warnings
ADD CONSTRAINT warnings_media_type_check
CHECK (media_type = ANY (ARRAY['image'::text, 'video'::text]));

-- ============================================================================
-- AGENDAMENTOS SERVER-SIDE (UTC: 03:00 == 00:00 America/Sao_Paulo)
-- ============================================================================

DO $$
DECLARE
  v_job_id bigint;
BEGIN
  SELECT jobid INTO v_job_id FROM cron.job WHERE jobname = 'display-runtime-cleanup-daily';
  IF v_job_id IS NOT NULL THEN
    PERFORM cron.unschedule(v_job_id);
  END IF;

  SELECT jobid INTO v_job_id FROM cron.job WHERE jobname = 'display-tts-cache-cleanup-daily';
  IF v_job_id IS NOT NULL THEN
    PERFORM cron.unschedule(v_job_id);
  END IF;
END
$$;

SELECT cron.schedule(
  'display-runtime-cleanup-daily',
  '0 3 * * *',
  $$SELECT public.display_cleanup_runtime();$$
);

SELECT cron.schedule(
  'display-tts-cache-cleanup-daily',
  '5 3 * * *',
  $$SELECT public.display_cleanup_tts_cache();$$
);

COMMIT;
